kind: pipeline
type: docker
name: testing

trigger:
  event:
    - pull_request
  branch:
    - testing

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

steps:
  - name: lint-html-css
    image: node:20-alpine
    commands:
      - npm install -g htmlhint stylelint stylelint-config-standard
      - htmlhint "htdocs/**/*.html"
      - stylelint "htdocs/**/*.css"

  - name: link-check
    image: docker.io/lycheeverse/lychee:0.15.1
    commands:
      - lychee --no-progress --timeout 20s --max-retries 2 --accept 200,206,301,302,429 --exclude "http://drone.kernelsanders.biz:8080" htdocs/index.html

  # Build testing docker image
  - name: testing-docker-build
    image: plugins/docker
    environment:
      DRONE_TAG: ${DRONE_TAG} # Get the tag value from Drone environment
    when:
      event:
        - pull_request
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/www.kernelsanders.biz
      tags:
        - testing-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}
        - testing-latest

  - name: smoke-test
    image: docker:24-cli
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - docker run --rm -d -p 8080:80 --name site-test kernel528/www.kernelsanders.biz:testing-latest
      - sleep 2
      - curl -f http://localhost:8080/
      - docker stop site-test

  # Post slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: main

trigger:
  event:
    - tag
  branch:
    - main

# Build the main docker image
steps:
  - name: main-docker-build
    image: plugins/docker
    environment:
      DRONE_TAG: ${DRONE_TAG}
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/www.kernelsanders.biz
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}
        - latest

  # When merged to main, test the latest image
  - name: main-image-test
    image: kernel528/www.kernelsanders.biz:latest
    when:
      branch:
        - main
    commands:
      - "cat /etc/alpine-release"
      - "httpd -v"
      - "curl www.kernelsanders.biz:81"

  # Post slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
